### ISSUE TITLE
如何才能序列化PageList<T>?

### ISSUE THREAD

**Issue by ghost** [Webdiyer/MvcCorePager#2]
如何才能Json序列化PageList<T>?
Redis缓存PageList<T>后，无法反序列化，缺少键值

**Comment by Webdiyer** [comment]
这个MvcCorePager中已经不再内建PagedList了，建议使用成熟的第三方的组件，比如[x.PagedList](https://github.com/dncuug/X.PagedList)，这些组件应该支持您说的功能。

**Comment by ghost** [comment]
不是有内建PagedList吗？x.PagedList好像也是个分页的，用它的话是不是就不用MvcCorePager了？

**Comment by Webdiyer** [comment]
@9527code MvcPager中有，MvcCorePager去掉了，PagedList只是保存分页数据的实体对象，并没有分页功能和用户界面

**Comment by ghost** [comment]
Src/PagedList.cs
不是吗？我的意思就是序列化分页数据的实体，之前用的内存缓存可以直接存，数据结构页正常。现在用Redis 存String  json序列化之后的json文本好像就是一个普通的List<T>实体，缺少int pageIndex, int pageSize, int totalItemCount 这三个属性，我现在的解决方案是存两个缓存，一个存PageList<T> 一个存TotalItemCount 。
虽然是先后一起存的，但是缓存时间还是有点误差，

读取的时候判断 listKey and countKey同时存在时再返回缓存数据，但是判断的时候两个都存在，读取的时候可能有其中一个已经过期， 想问下有没有办法存到一个实体类型中

**Comment by Webdiyer** [comment]
抱歉，记错了，是BlazorPager中去掉了PagedList!
您说的问题在所有实现了IEnumerable接口的对象中都存在，请看stackoverflow上的这个问题：[https://stackoverflow.com/questions/21265629/how-do-i-get-json-net-to-serialize-members-of-a-class-deriving-from-listt](https://stackoverflow.com/questions/21265629/how-do-i-get-json-net-to-serialize-members-of-a-class-deriving-from-listt)，其实解决办法就是现在您用的方法，x.PagedList用了一个自下定义的不包含分页数据的[PagedListMetaData](https://github.com/dncuug/X.PagedList/blob/master/src/X.PagedList/PagedListMetaData.cs)对象来传递这些分页相关属性，您可以参考一下，也可以直接使用x.PagedList来传递分页信息，MvcCorePager支持使用第三方的PagedList。谢谢！
